# Generated by Django 3.1.6 on 2022-01-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isHired',
            new_name='hired',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isAnEmployer',
            new_name='is_an_employer',
        ),
    ]
