# Generated by Django 3.1.6 on 2022-01-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_an_employer',
            new_name='isAnEmployer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hired',
        ),
        migrations.AddField(
            model_name='user',
            name='isHired',
            field=models.BooleanField(default=False, verbose_name='is_hired'),
        ),
    ]
