# Generated by Django 3.1.6 on 2022-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedJobs',
            field=models.ManyToManyField(blank=True, to='accounts.SavedJob'),
        ),
    ]
