# Generated by Django 3.1.6 on 2022-01-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220123_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_an_employer',
            new_name='isAnEmployer',
        ),
    ]
