# Generated by Django 3.1.6 on 2022-01-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220128_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hired',
            new_name='isHired',
        ),
    ]
