# Generated by Django 3.1.6 on 2022-09-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_savedjob_job'),
        ('jobseekers', '0012_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='savedJobs',
            field=models.ManyToManyField(blank=True, to='jobseekers.SavedJob'),
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
