# Generated by Django 3.1.6 on 2022-09-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220910_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='savedJobs',
        ),
    ]
