# Generated by Django 3.1.6 on 2022-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0017_savedjob_savedjob'),
        ('accounts', '0006_remove_user_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedJobs',
            field=models.ManyToManyField(blank=True, to='jobseekers.SavedJob'),
        ),
    ]
