# Generated by Django 3.1.6 on 2022-05-12 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to='CompanyLogosFiles')),
                ('banner', models.ImageField(blank=True, upload_to='CompanyBannerFiles')),
                ('industry', models.TextField(default='Any')),
                ('website', models.URLField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('salary1', models.CharField(max_length=10)),
                ('salary2', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(default='$', max_length=1)),
                ('industry', models.TextField(default='Any')),
                ('remote', models.BooleanField(default=False)),
                ('type', models.CharField(default='Full-time', max_length=9)),
                ('training', models.BooleanField(default=True)),
                ('positions', models.TextField(default='1')),
                ('education', models.CharField(max_length=50)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('workingDay1', models.CharField(default='Monday', max_length=10)),
                ('workingDay2', models.CharField(default='Friday', max_length=10)),
                ('workingHours', models.CharField(default='6', max_length=2)),
                ('applicantsCount', models.IntegerField(default=0)),
                ('applyOnOwnWebsite', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('datePosted', models.DateTimeField(auto_now_add=True, verbose_name='Job posted')),
                ('benefits', models.ManyToManyField(blank=True, to='employers.Benefit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.company')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, to='employers.Role')),
                ('skills', models.ManyToManyField(blank=True, to='main.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(blank=True, max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=250)),
                ('logo', models.ImageField(blank=True, upload_to='EmployerLogosFiles')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLetter', models.TextField(blank=True)),
                ('status', models.CharField(default='applied', max_length=8)),
                ('applicationDate', models.DateTimeField(auto_now_add=True, verbose_name='ApplicationDate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.job')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseekers.profile')),
            ],
        ),
    ]
