# Generated by Django 3.1.6 on 2022-06-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
