# Generated by Django 3.1.6 on 2022-05-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='employer',
        ),
    ]
