# Generated by Django 3.1.6 on 2022-06-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_job_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('years', models.IntegerField(max_length=2)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
    ]
