# Generated by Django 3.1.6 on 2022-02-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0002_auto_20220211_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to='CompanyLogosFiles')),
                ('banner', models.ImageField(blank=True, upload_to='CompanyBannerFiles')),
                ('industry', models.TextField(default='Any')),
                ('website', models.URLField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
