# Generated by Django 3.1.6 on 2022-06-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.IntegerField(),
        ),
    ]
