# Generated by Django 3.1.6 on 2022-03-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220120_2026'),
        ('employers', '0003_auto_20220215_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('salary', models.CharField(max_length=50)),
                ('industry', models.TextField(default='Any')),
                ('remote', models.BooleanField(default=False)),
                ('training', models.BooleanField(default=False)),
                ('positions', models.IntegerField(default=1)),
                ('education', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('workingDays', models.CharField(default='Monday-Friday', max_length=100)),
                ('workingHours', models.IntegerField(default=6)),
                ('applicantsCount', models.IntegerField(default=0)),
                ('datePosted', models.DateTimeField(auto_now_add=True, verbose_name='Job posted')),
                ('benefits', models.ManyToManyField(blank=True, to='employers.Benefit')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.company')),
                ('roles', models.ManyToManyField(to='employers.Role')),
                ('skills', models.ManyToManyField(blank=True, to='main.Skill')),
            ],
        ),
    ]
