# Generated by Django 3.1.6 on 2022-03-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='positions',
            field=models.TextField(default='1'),
        ),
    ]
