# Generated by Django 3.1.6 on 2022-03-11 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0006_auto_20220310_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='roles',
            field=models.ManyToManyField(blank=True, to='employers.Role'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='training',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
