# Generated by Django 3.1.6 on 2022-03-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_auto_20220311_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
