# Generated by Django 3.1.6 on 2022-03-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_auto_20220311_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applyOnOwnWebsite',
            field=models.BooleanField(default=False),
        ),
    ]
