# Generated by Django 3.1.6 on 2022-03-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_job_applyonownwebsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
