# Generated by Django 3.1.6 on 2022-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_auto_20220311_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
