# Generated by Django 3.1.6 on 2022-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_auto_20220311_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='Full-time', max_length=9),
        ),
    ]
