# Generated by Django 3.1.6 on 2022-03-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workingHours',
            field=models.CharField(default='6', max_length=2),
        ),
    ]
