# Generated by Django 3.1.6 on 2022-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0013_auto_20220319_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
