# Generated by Django 3.1.6 on 2022-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_auto_20220325_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='datePosted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Job posted'),
        ),
    ]
