# Generated by Django 3.1.6 on 2022-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0016_auto_20220326_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='workingDays',
        ),
        migrations.AddField(
            model_name='job',
            name='salary1',
            field=models.CharField(default=30000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='workingDay1',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='workingDay2',
            field=models.CharField(default='Friday', max_length=10),
        ),
    ]
