# Generated by Django 3.1.6 on 2022-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0017_auto_20220414_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(default='$', max_length=1),
        ),
    ]
