# Generated by Django 3.1.6 on 2022-04-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0007_auto_20220215_2112'),
        ('employers', '0018_job_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLetter', models.TextField()),
                ('applicationDate', models.DateTimeField(auto_now_add=True, verbose_name='ApplicationDate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekers.profile')),
            ],
        ),
    ]
