# Generated by Django 3.1.6 on 2022-04-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0019_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='coverLetter',
            field=models.TextField(blank=True),
        ),
    ]
