# Generated by Django 3.1.6 on 2022-05-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0007_auto_20220215_2112'),
        ('employers', '0020_auto_20220427_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseekers.profile'),
        ),
    ]
