# Generated by Django 3.1.6 on 2022-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0021_auto_20220501_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='applied', max_length=8),
        ),
    ]
