# Generated by Django 3.1.6 on 2022-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_generic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='generic',
        ),
        migrations.AddField(
            model_name='skill',
            name='specific',
            field=models.BooleanField(default=False),
        ),
    ]
