# Generated by Django 3.1.6 on 2022-05-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(blank=True, max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to='profileLogosFiles')),
                ('cv', models.FileField(blank=True, upload_to='cvFiles')),
                ('education', models.CharField(max_length=50)),
                ('industry', models.TextField(default='Any')),
                ('distance', models.TextField(default='Any')),
                ('experience', models.TextField(blank=True)),
                ('about', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(blank=True, to='main.Skill')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
