# Generated by Django 3.1.6 on 2022-01-12 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=11)),
                ('postcode', models.CharField(max_length=8)),
                ('cv', models.FileField(blank=True, upload_to='cv_files')),
                ('resume', models.FileField(blank=True, upload_to='resume_files')),
                ('skills', models.TextField()),
                ('education', models.CharField(max_length=50)),
                ('sectors', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('experience', models.TextField(blank=True)),
                ('about', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
