# Generated by Django 3.1.6 on 2022-01-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postcode',
        ),
    ]
