# Generated by Django 3.1.6 on 2022-01-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220120_2026'),
        ('jobseekers', '0002_auto_20220120_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main.Skill'),
        ),
    ]
