# Generated by Django 3.1.6 on 2022-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_profileexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileexperience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profileexperience',
            name='reference',
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='companyEmail',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='companyPhone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
