# Generated by Django 3.1.6 on 2022-07-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0003_auto_20220626_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileexperience',
            old_name='companyEmail',
            new_name='EmployerEmail',
        ),
        migrations.RenameField(
            model_name='profileexperience',
            old_name='companyName',
            new_name='EmployerName',
        ),
        migrations.RenameField(
            model_name='profileexperience',
            old_name='companyPhone',
            new_name='EmployerPhone',
        ),
    ]
