# Generated by Django 3.1.6 on 2022-07-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0005_auto_20220703_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileexperience',
            name='companyName',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
