# Generated by Django 3.1.6 on 2022-02-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0005_auto_20220122_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middleName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
