# Generated by Django 3.1.6 on 2022-07-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0006_profileexperience_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileexperience',
            name='companyName',
        ),
    ]
