# Generated by Django 3.1.6 on 2022-07-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0008_profileexperience_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileexperience',
            old_name='ongoing',
            new_name='isOnGoing',
        ),
    ]
