# Generated by Django 3.1.6 on 2022-07-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0009_auto_20220706_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='No formal education', max_length=50),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseekers.profile'),
        ),
    ]
