# Generated by Django 3.1.6 on 2022-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0010_auto_20220729_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileexperience',
            name='EmployerName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
