# Generated by Django 3.1.6 on 2022-09-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0012_savedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='job',
            new_name='savedJob',
        ),
    ]
