# Generated by Django 3.1.6 on 2022-09-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_company_isactive'),
        ('jobseekers', '0014_delete_savedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savedDate', models.DateTimeField(auto_now_add=True, verbose_name='savedDate')),
                ('savedJob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.job')),
            ],
        ),
    ]
