# Generated by Django 3.1.6 on 2022-09-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0015_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='savedJob',
        ),
    ]
