# Generated by Django 3.1.6 on 2022-09-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0017_savedjob_savedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='savedJob',
            new_name='job',
        ),
    ]
