# Generated by Django 3.1.6 on 2022-10-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0018_auto_20220910_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('field', models.TextField(blank=True)),
                ('school', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('currentlyEnrolled', models.BooleanField(default=False)),
                ('fromDate', models.CharField(blank=True, max_length=200)),
                ('toDate', models.CharField(blank=True, max_length=200)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseekers.profile')),
            ],
        ),
    ]
