# Generated by Django 3.1.6 on 2023-01-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0021_profileeducation_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileeducation',
            name='fromDate',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='profileeducation',
            name='toDate',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
